return {
    'nvim-treesitter/nvim-treesitter',
    branch = 'master',
    lazy = false,
    build = ":TSUpdate",
    main = 'nvim-treesitter.configs',
    opts = {
        highlight = { enable = true },
        indent = { enable = true },
        ensure_installed = {
            "lua",
            "tsx",
            "typescript",
            "php",
            "query",
            "java",
            "c",
            "python",
            "go",
            "haskell",
            "markdown",
            "markdown_inline",
        },
        auto_install = false,
    },
}
